------------------------------------------------------------
-- To enable support for some non-standard syntax of Oracle
------------------------------------------------------------
SET DATABASE SQL SYNTAX ORA TRUE;

DROP TABLE ADDRESS
IF EXISTS;

CREATE TABLE ADDRESS(
  id             NUMBER (19, 0) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) PRIMARY KEY,
  building       VARCHAR(50),
  street         VARCHAR(50),
  town           VARCHAR(50),
  county         VARCHAR(50),
  postcode       VARCHAR(50)
);